version: 2.1
jobs:
  build:
    working_directory: ~/cours-l2
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout
      - run:
          name: install jest
          command: yarn global add jest
      - run:
          name: test javascript exercices
          command: ~/.yarn/bin/jest javascript/test.js
      - store_artifacts:
          path: test-results.xml
          prefix: tests
