version: 2.1
jobs:
  build:
    working_directory: ~/cours-l2
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install -g npm'
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: install-dep
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: test javascript exercices
          command: jest javascript/test.js
      - store_artifacts:
          path: test-results.xml
          prefix: tests
